### ISSUE TITLE
Configure Menu Bar

### ISSUE THREAD

**Issue by TrevorSayre** [ThatNerdSquared/timers-for-raycast#13]
Currently the Menu Bar display shows a tilde to indicate approximate time left as it doesn't tick at a 1 second interval. I have other Menu Bar apps which do tick at a 1 second interval for timers, so I'm unsure if this decision is technical or design. Additionally the tilde takes up some extra space as does the hour indicator when I'm using timers that are less than an hour. Would it be possible to allow configuring these features?

- Configure approximate or exact update interval (tilde only shows for approximate)
- Configure display format to include hours or not for timers under 1 hour
- Configure icon (could have other options, or just "show / don't show" toggle)

Really great work on this extension! Love all the features you've built in so far.

**Comment by ThatNerdSquared** [comment]
Hi @TrevorSayre, thanks for using Timers!

The menu bar ticks at a 10 second interval. This is because it's handled by Raycast's background refresh, which [doesn't allow refresh intervals faster than 10 seconds](https://developers.raycast.com/information/lifecycle/background-refresh#manifest), presumably for performance reasons. I don't know of any workarounds for it so I won't be able to provide any solutions in that department \:(

> - Configure display format to include hours or not for timers under 1 hour
> - Configure icon (could have other options, or just "show / don't show" toggle)

These are good ideas! I'll implement them for the next update. Thanks for the suggestions :)

**Comment by ThatNerdSquared** [comment]
Update: the already-released `Show Menu Bar Item When` pref may work for you in terms of hiding the icon. The name is a bit unclear, I'll rename it to "Show Menu Bar **Icon** When" in the next release.

It also doesn't yet have an option for showing icon when there are no timers, and hiding icon when there are timers - that is coming in the next update.

**Comment by ThatNerdSquared** [comment]
Alright, my latest changes have been released. The extension now has an updated "Show Menu Bar Icon" pref - the "Only When Not Running" should give you your desired result (show the icon when no timer is running, but hide it when one is).

![Screenshot 2024-01-23 at 13 11 45](https://github.com/ThatNerdSquared/timers-for-raycast/assets/72814106/3cddca23-5a4f-416c-b951-8faf4d6ec42e)

I've also changed the display format to not display hours for timers/stopwatches <1hr.

Closing this issue now, feel free to reopen/file a new one if the new solutions don't work for you, or you have another request :)
