### ISSUE TITLE
Menu bar update interval

### ISSUE THREAD

**Issue by mortan** [ThatNerdSquared/timers-for-raycast#23]
Hi! I'm really liking the plugin, but one thing that irritates me is the "~1:20" label in the menubar that seems to refresh itself around every 10 seconds (?). Is there a way to have an update interval of 1 second like in a "normal" timer?

Thanks for the help!

**Comment by ThatNerdSquared** [comment]
Hi @mortan, thanks for using Timers!

Unfortunately, the 10-second refresh interval is a limitation imposed by Raycast. Since the [minimum refresh interval allowed by the Raycast API is 10 seconds](https://developers.raycast.com/information/lifecycle/background-refresh#manifest), there's not much I can do to have it update every second from an extension developer standpoint.

I'd suggest putting a suggestion in the [Raycast Slack](https://raycastcommunity.slack.com/) if you'd like to see the Raycast team work on something to lift this limitation - if the API is updated I will update Timers accordingly. Sorry about that :(

**Comment by mortan** [comment]
No worries and thanks for the explanation! I'll see if someone already suggested the change for the Raycast API, otherwise I'll suggest it!
